// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Contacts.proto

package com.liangquan.InterviewQuestion.A01_序列化和反序列化.A01_2_protoUsersPlus.Contacts;

public interface ContactsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto3.Contacts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto3.UserPlus users = 1;</code>
   */
  java.util.List<UserPlus>
      getUsersList();
  /**
   * <code>repeated .proto3.UserPlus users = 1;</code>
   */
  UserPlus getUsers(int index);
  /**
   * <code>repeated .proto3.UserPlus users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .proto3.UserPlus users = 1;</code>
   */
  java.util.List<? extends UserPlusOrBuilder>
      getUsersOrBuilderList();
  /**
   * <code>repeated .proto3.UserPlus users = 1;</code>
   */
  UserPlusOrBuilder getUsersOrBuilder(
      int index);
}
