// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Contacts.proto

package com.liangquan.InterviewQuestion.A01_序列化和反序列化.A01_2_protoUsersPlus.Contacts;

/**
 * <pre>
 * 定义 单个联系人 message
 * </pre>
 *
 * Protobuf type {@code proto3.UserPlus}
 */
public final class UserPlus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto3.UserPlus)
    UserPlusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserPlus.newBuilder() to construct.
  private UserPlus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserPlus() {
    name_ = "";
    phone_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserPlus();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ContactsOuterClass.internal_static_proto3_UserPlus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ContactsOuterClass.internal_static_proto3_UserPlus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UserPlus.class, UserPlus.Builder.class);
  }

  public interface PhoneOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto3.UserPlus.Phone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();
  }
  /**
   * Protobuf type {@code proto3.UserPlus.Phone}
   */
  public static final class Phone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto3.UserPlus.Phone)
      PhoneOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Phone.newBuilder() to construct.
    private Phone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Phone() {
      number_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Phone();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ContactsOuterClass.internal_static_proto3_UserPlus_Phone_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ContactsOuterClass.internal_static_proto3_UserPlus_Phone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserPlus.Phone.class, UserPlus.Phone.Builder.class);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object number_ = "";
    /**
     * <code>string number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserPlus.Phone)) {
        return super.equals(obj);
      }
      UserPlus.Phone other = (UserPlus.Phone) obj;

      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserPlus.Phone parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserPlus.Phone parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserPlus.Phone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserPlus.Phone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserPlus.Phone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserPlus.Phone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserPlus.Phone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserPlus.Phone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserPlus.Phone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static UserPlus.Phone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserPlus.Phone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static UserPlus.Phone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserPlus.Phone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto3.UserPlus.Phone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto3.UserPlus.Phone)
        UserPlus.PhoneOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ContactsOuterClass.internal_static_proto3_UserPlus_Phone_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ContactsOuterClass.internal_static_proto3_UserPlus_Phone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserPlus.Phone.class, UserPlus.Phone.Builder.class);
      }

      // Construct using com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts.UserPlus.Phone.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        number_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ContactsOuterClass.internal_static_proto3_UserPlus_Phone_descriptor;
      }

      @java.lang.Override
      public UserPlus.Phone getDefaultInstanceForType() {
        return UserPlus.Phone.getDefaultInstance();
      }

      @java.lang.Override
      public UserPlus.Phone build() {
        UserPlus.Phone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public UserPlus.Phone buildPartial() {
        UserPlus.Phone result = new UserPlus.Phone(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(UserPlus.Phone result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.number_ = number_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserPlus.Phone) {
          return mergeFrom((UserPlus.Phone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserPlus.Phone other) {
        if (other == UserPlus.Phone.getDefaultInstance()) return this;
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                number_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object number_ = "";
      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        number_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        number_ = getDefaultInstance().getNumber();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string number = 1;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        number_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto3.UserPlus.Phone)
    }

    // @@protoc_insertion_point(class_scope:proto3.UserPlus.Phone)
    private static final UserPlus.Phone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserPlus.Phone();
    }

    public static UserPlus.Phone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Phone>
        PARSER = new com.google.protobuf.AbstractParser<Phone>() {
      @java.lang.Override
      public Phone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Phone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Phone> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public UserPlus.Phone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_ = 0;
  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  @java.lang.Override
  public int getAge() {
    return age_;
  }

  public static final int PHONE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<UserPlus.Phone> phone_;
  /**
   * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
   */
  @java.lang.Override
  public java.util.List<UserPlus.Phone> getPhoneList() {
    return phone_;
  }
  /**
   * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends UserPlus.PhoneOrBuilder>
      getPhoneOrBuilderList() {
    return phone_;
  }
  /**
   * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
   */
  @java.lang.Override
  public int getPhoneCount() {
    return phone_.size();
  }
  /**
   * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
   */
  @java.lang.Override
  public UserPlus.Phone getPhone(int index) {
    return phone_.get(index);
  }
  /**
   * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
   */
  @java.lang.Override
  public UserPlus.PhoneOrBuilder getPhoneOrBuilder(
      int index) {
    return phone_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (age_ != 0) {
      output.writeInt32(2, age_);
    }
    for (int i = 0; i < phone_.size(); i++) {
      output.writeMessage(3, phone_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, age_);
    }
    for (int i = 0; i < phone_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, phone_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UserPlus)) {
      return super.equals(obj);
    }
    UserPlus other = (UserPlus) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getAge()
        != other.getAge()) return false;
    if (!getPhoneList()
        .equals(other.getPhoneList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    if (getPhoneCount() > 0) {
      hash = (37 * hash) + PHONE_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UserPlus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UserPlus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UserPlus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UserPlus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UserPlus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UserPlus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UserPlus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UserPlus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UserPlus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UserPlus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UserPlus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UserPlus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UserPlus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 定义 单个联系人 message
   * </pre>
   *
   * Protobuf type {@code proto3.UserPlus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto3.UserPlus)
          UserPlusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ContactsOuterClass.internal_static_proto3_UserPlus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ContactsOuterClass.internal_static_proto3_UserPlus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserPlus.class, UserPlus.Builder.class);
    }

    // Construct using com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts.UserPlus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      age_ = 0;
      if (phoneBuilder_ == null) {
        phone_ = java.util.Collections.emptyList();
      } else {
        phone_ = null;
        phoneBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ContactsOuterClass.internal_static_proto3_UserPlus_descriptor;
    }

    @java.lang.Override
    public UserPlus getDefaultInstanceForType() {
      return UserPlus.getDefaultInstance();
    }

    @java.lang.Override
    public UserPlus build() {
      UserPlus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public UserPlus buildPartial() {
      UserPlus result = new UserPlus(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(UserPlus result) {
      if (phoneBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          phone_ = java.util.Collections.unmodifiableList(phone_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.phone_ = phone_;
      } else {
        result.phone_ = phoneBuilder_.build();
      }
    }

    private void buildPartial0(UserPlus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.age_ = age_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UserPlus) {
        return mergeFrom((UserPlus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UserPlus other) {
      if (other == UserPlus.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (phoneBuilder_ == null) {
        if (!other.phone_.isEmpty()) {
          if (phone_.isEmpty()) {
            phone_ = other.phone_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePhoneIsMutable();
            phone_.addAll(other.phone_);
          }
          onChanged();
        }
      } else {
        if (!other.phone_.isEmpty()) {
          if (phoneBuilder_.isEmpty()) {
            phoneBuilder_.dispose();
            phoneBuilder_ = null;
            phone_ = other.phone_;
            bitField0_ = (bitField0_ & ~0x00000004);
            phoneBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhoneFieldBuilder() : null;
          } else {
            phoneBuilder_.addAllMessages(other.phone_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              age_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              UserPlus.Phone m =
                  input.readMessage(
                      UserPlus.Phone.parser(),
                      extensionRegistry);
              if (phoneBuilder_ == null) {
                ensurePhoneIsMutable();
                phone_.add(m);
              } else {
                phoneBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      
      age_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      bitField0_ = (bitField0_ & ~0x00000002);
      age_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<UserPlus.Phone> phone_ =
      java.util.Collections.emptyList();
    private void ensurePhoneIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        phone_ = new java.util.ArrayList<UserPlus.Phone>(phone_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        UserPlus.Phone, UserPlus.Phone.Builder, UserPlus.PhoneOrBuilder> phoneBuilder_;

    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public java.util.List<UserPlus.Phone> getPhoneList() {
      if (phoneBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phone_);
      } else {
        return phoneBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public int getPhoneCount() {
      if (phoneBuilder_ == null) {
        return phone_.size();
      } else {
        return phoneBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public UserPlus.Phone getPhone(int index) {
      if (phoneBuilder_ == null) {
        return phone_.get(index);
      } else {
        return phoneBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public Builder setPhone(
        int index, UserPlus.Phone value) {
      if (phoneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.set(index, value);
        onChanged();
      } else {
        phoneBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public Builder setPhone(
        int index, UserPlus.Phone.Builder builderForValue) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.set(index, builderForValue.build());
        onChanged();
      } else {
        phoneBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public Builder addPhone(UserPlus.Phone value) {
      if (phoneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.add(value);
        onChanged();
      } else {
        phoneBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public Builder addPhone(
        int index, UserPlus.Phone value) {
      if (phoneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneIsMutable();
        phone_.add(index, value);
        onChanged();
      } else {
        phoneBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public Builder addPhone(
        UserPlus.Phone.Builder builderForValue) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.add(builderForValue.build());
        onChanged();
      } else {
        phoneBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public Builder addPhone(
        int index, UserPlus.Phone.Builder builderForValue) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.add(index, builderForValue.build());
        onChanged();
      } else {
        phoneBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public Builder addAllPhone(
        java.lang.Iterable<? extends UserPlus.Phone> values) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phone_);
        onChanged();
      } else {
        phoneBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public Builder clearPhone() {
      if (phoneBuilder_ == null) {
        phone_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        phoneBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public Builder removePhone(int index) {
      if (phoneBuilder_ == null) {
        ensurePhoneIsMutable();
        phone_.remove(index);
        onChanged();
      } else {
        phoneBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public UserPlus.Phone.Builder getPhoneBuilder(
        int index) {
      return getPhoneFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public UserPlus.PhoneOrBuilder getPhoneOrBuilder(
        int index) {
      if (phoneBuilder_ == null) {
        return phone_.get(index);  } else {
        return phoneBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public java.util.List<? extends UserPlus.PhoneOrBuilder>
         getPhoneOrBuilderList() {
      if (phoneBuilder_ != null) {
        return phoneBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phone_);
      }
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public UserPlus.Phone.Builder addPhoneBuilder() {
      return getPhoneFieldBuilder().addBuilder(
          UserPlus.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public UserPlus.Phone.Builder addPhoneBuilder(
        int index) {
      return getPhoneFieldBuilder().addBuilder(
          index, UserPlus.Phone.getDefaultInstance());
    }
    /**
     * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
     */
    public java.util.List<UserPlus.Phone.Builder>
         getPhoneBuilderList() {
      return getPhoneFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        UserPlus.Phone, UserPlus.Phone.Builder, UserPlus.PhoneOrBuilder>
        getPhoneFieldBuilder() {
      if (phoneBuilder_ == null) {
        phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            UserPlus.Phone, UserPlus.Phone.Builder, UserPlus.PhoneOrBuilder>(
                phone_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        phone_ = null;
      }
      return phoneBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto3.UserPlus)
  }

  // @@protoc_insertion_point(class_scope:proto3.UserPlus)
  private static final UserPlus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UserPlus();
  }

  public static UserPlus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserPlus>
      PARSER = new com.google.protobuf.AbstractParser<UserPlus>() {
    @java.lang.Override
    public UserPlus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserPlus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserPlus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public UserPlus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

