// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Contacts.proto

package com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts;

public interface ContactsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto3.Contacts)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .proto3.UserPlus users = 1;</code>
   */
  java.util.List<com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts.UserPlus> 
      getUsersList();
  /**
   * <code>repeated .proto3.UserPlus users = 1;</code>
   */
  com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts.UserPlus getUsers(int index);
  /**
   * <code>repeated .proto3.UserPlus users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .proto3.UserPlus users = 1;</code>
   */
  java.util.List<? extends com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts.UserPlusOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .proto3.UserPlus users = 1;</code>
   */
  com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts.UserPlusOrBuilder getUsersOrBuilder(
      int index);
}
