// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Contacts.proto

package com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts;

public interface UserPlusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto3.UserPlus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
   */
  java.util.List<com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts.UserPlus.Phone> 
      getPhoneList();
  /**
   * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
   */
  com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts.UserPlus.Phone getPhone(int index);
  /**
   * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
   */
  int getPhoneCount();
  /**
   * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
   */
  java.util.List<? extends com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts.UserPlus.PhoneOrBuilder> 
      getPhoneOrBuilderList();
  /**
   * <code>repeated .proto3.UserPlus.Phone phone = 3;</code>
   */
  com.liangquan.InterviewQuestion.A03_protoUsersPlus.Contacts.UserPlus.PhoneOrBuilder getPhoneOrBuilder(
      int index);
}
