// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.liangquan.InterviewQuestion.A01_序列化和反序列化.A01_1_protoBuf.ProtoUsers;

public interface ProtoUsersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usersStart.ProtoUsers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 字段类型 字段名 = 字段唯一编号；
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>int32 age = 4;</code>
   * @return The age.
   */
  int getAge();
}
