// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.liangquan.InterviewQuestion.A01_序列化和反序列化.A01_1_protoBuf.ProtoUsers;

public final class UsersProtos {
  private UsersProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usersStart_ProtoUsers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usersStart_ProtoUsers_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\nusersStart\"E\n\nProtoUsers\022\n" +
      "\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010password\030\003 \001" +
      "(\t\022\013\n\003age\030\004 \001(\005BH\n7com.liangquan.Intervi" +
      "ewQuestion.A02_protoBuf.ProtoUsersB\013User" +
      "sProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_usersStart_ProtoUsers_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_usersStart_ProtoUsers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usersStart_ProtoUsers_descriptor,
        new java.lang.String[] { "Id", "Name", "Password", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
